kubernetes_schema_excluded_kinds = [
  "AKSNodeClass",
  "CiliumNetworkPolicy",
  "Component",
  "ContainerNetworkLog",
  "Gateway",
  "HTTPRoute",
  "Instrumentation",
  "Kustomization",
  "NodePool",
  "VerticalPodAutoscaler",
]
