from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]


def dependabot_update_blocks() -> tuple[dict[str, Any], dict[str, dict[str, Any]]]:
    config = yaml.safe_load(
        (REPO_ROOT / ".github" / "dependabot.yml").read_text(encoding="utf-8")
    )
    return config, {update["package-ecosystem"]: update for update in config["updates"]}


def test_dependabot_contract() -> None:
    config, blocks = dependabot_update_blocks()

    assert config["version"] == 2
    assert set(blocks) == {"github-actions", "docker"}

    for ecosystem, limit in (("github-actions", 5), ("docker", 3)):
        block = blocks[ecosystem]
        assert block["schedule"]["interval"] == "weekly"
        assert block["open-pull-requests-limit"] == limit
        group = next(iter(block["groups"].values()))
        assert group["patterns"] == ["*"]
        assert group["update-types"] == ["minor", "patch"]


def test_dependabot_excludes_generated_and_uv_managed_inputs() -> None:
    _, blocks = dependabot_update_blocks()

    actions = blocks["github-actions"]
    assert actions["directory"] == "/"
    assert actions["exclude-paths"] == [".github/workflows/*.lock.yml"]
    action_ignores = {item["dependency-name"] for item in actions["ignore"]}
    assert "github/gh-aw-actions/*" in action_ignores

    docker = blocks["docker"]
    assert docker["directory"] == "/src/api"
    docker_ignores = {item["dependency-name"] for item in docker["ignore"]}
    assert docker_ignores == {"ghcr.io/astral-sh/uv"}


def test_ci_runs_repository_health_check() -> None:
    ci = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")

    assert 'scripts/tasks.py" check-repo-health' in ci


def test_freshness_workflow_contract() -> None:
    source = (
        REPO_ROOT / ".github" / "workflows" / "repository-freshness-check.md"
    ).read_text(encoding="utf-8")

    assert "schedule: weekly" in source
    assert "workflow_dispatch:" in source
    assert "permissions:\n  contents: read\n  copilot-requests: write" in source
    assert "safe-outputs:\n  create-issue:" in source
    assert "close-older-issues: true" in source
    assert "max: 1" in source
    assert "repository-freshness-checker/SKILL.md" in source

    subjects = (
        "gh-aw",
        "Lefthook",
        "actionlint",
        "kubeconform",
        "azd",
        "Chaos Mesh Helm chart",
    )
    for subject in subjects:
        assert subject in source
    for boundary in (
        "bicep-version-check.yml",
        "aks-updates-analyzer",
        "GitHub ActionsとDocker",
        "Dependabot",
    ):
        assert boundary in source

    for forbidden in (
        "azure/login",
        "az login",
        "create-pull-request:",
        "push-to-pr-branch:",
        "contents: write",
    ):
        assert forbidden not in source


def test_freshness_targets_exist_in_repository_inventory() -> None:
    completed = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "repo_health.py"),
            "inventory",
            "--format",
            "json",
        ],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    inventory = json.loads(completed.stdout)["inventory"]
    tool_versions = {
        item["location"].rpartition(":")[2]
        for item in inventory
        if item["category"] == "tool-version"
    }
    helm_charts = {
        item["value"] for item in inventory if item["category"] == "helm-chart"
    }
    gh_aw_versions = {
        item["value"]
        for item in inventory
        if item["location"].endswith(("gh-aw-setup", "compiler-version"))
    }

    assert {"lefthook", "actionlint", "kubeconform", "azd"} <= tool_versions
    assert "chaos-mesh/chaos-mesh" in helm_charts
    assert gh_aw_versions


def test_freshness_workflow_is_compiled() -> None:
    lock = (
        REPO_ROOT / ".github" / "workflows" / "repository-freshness-check.lock.yml"
    ).read_text(encoding="utf-8")

    assert "automatically generated by gh-aw" in lock
    assert "schedule:" in lock
    assert "workflow_dispatch:" in lock
    assert "issues: write" in lock
    assert "pull-requests: write" not in lock
    assert "id-token: write" not in lock


def test_documentation_exposes_maintenance_entry_points() -> None:
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    deployment = (REPO_ROOT / "docs" / "deployment.md").read_text(encoding="utf-8")

    assert "review-repo-fast" in readme
    assert "review-repo-full" in readme
    assert ".github/dependabot.yml" in readme
    assert "bicep-version-check.yml" in readme
    assert "aks-updates-analyzer.md" in readme
    assert "repository-freshness-check.md" in readme

    assert "Dependabotのuv ecosystemは現時点では有効にしません" in deployment
    assert 'resolution-strategy = "lowest"' in deployment
    assert "workspace member" in deployment
    assert "public PyPI" in deployment
    assert "check-public-lock" in deployment
    assert "check-publisher-requirements" in deployment
    assert "refresh-uv-lock.yml" in deployment
