from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def dependabot_update_blocks() -> dict[str, str]:
    text = (REPO_ROOT / ".github" / "dependabot.yml").read_text(encoding="utf-8")
    matches = list(
        re.finditer(
            r'^  - package-ecosystem: "([^"]+)"$',
            text,
            flags=re.MULTILINE,
        )
    )
    return {
        match.group(1): text[
            match.start() : matches[index + 1].start()
            if index + 1 < len(matches)
            else len(text)
        ]
        for index, match in enumerate(matches)
    }


def test_dependabot_contract() -> None:
    path = REPO_ROOT / ".github" / "dependabot.yml"
    text = path.read_text(encoding="utf-8")
    blocks = dependabot_update_blocks()

    assert text.startswith("version: 2\nupdates:\n")
    assert set(blocks) == {"github-actions", "docker"}
    assert 'package-ecosystem: "uv"' not in text

    for ecosystem, limit in (("github-actions", 5), ("docker", 3)):
        block = blocks[ecosystem]
        assert 'interval: "weekly"' in block
        assert f"open-pull-requests-limit: {limit}" in block
        assert "groups:" in block
        assert '          - "*"' in block
        assert '          - "minor"' in block
        assert '          - "patch"' in block


def test_dependabot_excludes_generated_and_uv_managed_inputs() -> None:
    text = (REPO_ROOT / ".github" / "dependabot.yml").read_text(encoding="utf-8")
    blocks = dependabot_update_blocks()

    actions = blocks["github-actions"]
    assert 'directory: "/"' in actions
    assert "exclude-paths:" in actions
    assert '".github/workflows/*.lock.yml"' in actions
    assert ".github/aw/actions-lock.json" in text
    assert "`gh aw compile`" in text

    docker = blocks["docker"]
    assert 'directory: "/src/api"' in docker
    assert "ignore:" in docker
    assert 'dependency-name: "astral-sh/uv"' in docker
    assert "check-uv-version" in docker


def test_freshness_workflow_contract() -> None:
    source = (
        REPO_ROOT / ".github" / "workflows" / "repository-freshness-check.md"
    ).read_text(encoding="utf-8")

    assert "schedule: weekly" in source
    assert "workflow_dispatch:" in source
    assert "permissions:\n  contents: read\n  copilot-requests: write" in source
    assert "safe-outputs:\n  create-issue:" in source
    assert "close-older-issues: true" in source
    assert "max: 1" in source
    assert "repository-freshness-checker/SKILL.md" in source

    subjects = (
        "gh-aw",
        "Lefthook",
        "actionlint",
        "kubeconform",
        "azd",
        "Chaos Mesh Helm chart",
    )
    for subject in subjects:
        assert subject in source
    for boundary in (
        "bicep-version-check.yml",
        "aks-updates-analyzer",
        "GitHub ActionsとDocker",
        "Dependabot",
    ):
        assert boundary in source

    for forbidden in (
        "azure/login",
        "az login",
        "create-pull-request:",
        "push-to-pr-branch:",
        "contents: write",
    ):
        assert forbidden not in source


def test_freshness_targets_exist_in_repository_inventory() -> None:
    completed = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "repo_health.py"),
            "inventory",
            "--format",
            "json",
        ],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    inventory = json.loads(completed.stdout)["inventory"]
    tool_versions = {
        item["location"].rpartition(":")[2]
        for item in inventory
        if item["category"] == "tool-version"
    }
    helm_charts = {
        item["value"] for item in inventory if item["category"] == "helm-chart"
    }
    gh_aw_versions = {
        item["value"]
        for item in inventory
        if item["location"].endswith(("gh-aw-setup", "compiler-version"))
    }

    assert {"lefthook", "actionlint", "kubeconform", "azd"} <= tool_versions
    assert "chaos-mesh/chaos-mesh" in helm_charts
    assert gh_aw_versions


def test_freshness_workflow_is_compiled() -> None:
    lock = (
        REPO_ROOT / ".github" / "workflows" / "repository-freshness-check.lock.yml"
    ).read_text(encoding="utf-8")

    assert "automatically generated by gh-aw" in lock
    assert "schedule:" in lock
    assert "workflow_dispatch:" in lock
    assert "issues: write" in lock
    assert "pull-requests: write" not in lock
    assert "id-token: write" not in lock


def test_documentation_exposes_maintenance_entry_points() -> None:
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    deployment = (REPO_ROOT / "docs" / "deployment.md").read_text(encoding="utf-8")

    assert "review-repo-fast" in readme
    assert "review-repo-full" in readme
    assert ".github/dependabot.yml" in readme
    assert "bicep-version-check.yml" in readme
    assert "aks-updates-analyzer.md" in readme
    assert "repository-freshness-check.md" in readme

    assert "Dependabotのuv ecosystemは現時点では有効にしません" in deployment
    assert 'resolution-strategy = "lowest"' in deployment
    assert "workspace member" in deployment
    assert "public PyPI" in deployment
    assert "check-public-lock" in deployment
    assert "check-publisher-requirements" in deployment
    assert "refresh-uv-lock.yml" in deployment
